deploy-package:
    stage: deploy
    image: python:3.8-slim
    variables:
      TWINE_USERNAME: "${CAPELLA_PYPI_SVC_USER}"
      TWINE_PASSWORD: "${CAPELLA_PYPI_SVC_PASS}"
      TWINE_REPOSITORY_URL: "${CAPELLA_PYPI_REPO_URL}"
    script:
      - pip install twine
      - python setup.py sdist
      - twine upload --verbose dist/*
    only:
      - tags
  