__version__ = '0.2.3'
__author__ = 'Dan Regan'
__author_email__ = 'dan.regan@capellaspace.com'
__description__ = 'Visual Studio Debug Helper'
__url__ = 'https://gitlab.corp.capellaspace.com/GroundSoftware/vsdbg'
