# Do not edit this file. It will be auto-generated by Gitlab
# Instead, make changes to vsdbg/vsdbg.py, which will be copied here.

import debugpy

PORT = 5678

def dbg(port=PORT, wait=True):
    debugpy.listen(port)
    if wait: debugpy.wait_for_client()